name: Development

on: [push, pull_request]

permissions:
  contents: read

env:
  CONSOLE_OUTPUT: Text

jobs:
  test:
    name: ${{matrix.ruby}} on ${{matrix.os}} ${{matrix.env}}
    runs-on: ${{matrix.os}}-latest
    continue-on-error: ${{matrix.experimental}}
    
    strategy:
      matrix:
        os:
          - ubuntu
          - macos
        
        ruby:
          - "3.1"
        
        experimental: [false]
        env: [""]
        
        include:
          - os: ubuntu
            ruby: truffleruby
            experimental: true
          - os: ubuntu
            ruby: jruby
            experimental: true
          - os: ubuntu
            ruby: head
            experimental: true
          - os: ubuntu
            ruby: head
            experimental: false
            env: "IO_EVENT_SELECTOR=Select"

    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{matrix.ruby}}
        bundler-cache: true
    
    - name: Run tests
      timeout-minutes: 5
      run: ${{matrix.env}} bundle exec rspec
